sonar.projectKey=allanahrazanakoto_Skillhub
sonar.organization=allanahrazanakoto
sonar.projectName=Skillhub

sonar.sources=skillhub_back/app
sonar.tests=skillhub_back/tests
sonar.php.coverage.reportPaths=skillhub_back/coverage.xml
sonar.exclusions=skillhub_back/vendor/**,skillhub_back/node_modules/**,skillhub_back/public/**
