sonar.projectKey=skillhub_Skillhub
sonar.organization=skillhub
sonar.projectName=Skillhub
sonar.projectVersion=1.0

sonar.sources=skillhub_back/app,skillhub_auth/src/main,skillhub_front/src
sonar.tests=skillhub_back/tests,skillhub_auth/src/test

sonar.php.file.suffixes=.php
sonar.java.source=21
sonar.java.binaries=skillhub_auth/target/classes

sonar.javascript.lcov.reportPaths=skillhub_front/coverage/lcov.info
sonar.php.coverage.reportPaths=skillhub_back/reports/coverage.xml
