sonar.projectKey=allanahrazanakoto_Skillhub
sonar.organization=allanahrazanakoto
sonar.projectName=Skillhub
sonar.projectVersion=1.0

sonar.sources=skillhub_back/app,skillhub_auth/src/main
sonar.tests=skillhub_back/tests,skillhub_auth/src/test
sonar.exclusions=skillhub_auth/src/main/java/com/example/auth/client/**

sonar.php.file.suffixes=.php
sonar.java.source=21
sonar.java.binaries=skillhub_auth/target/classes
sonar.coverage.jacoco.xmlReportPaths=skillhub_auth/target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=skillhub_back/app/Http/**,skillhub_back/app/Services/ActivityLogService.php,skillhub_auth/src/main/java/com/example/auth/AuthApplication.java,skillhub_auth/src/main/java/com/example/auth/client/**,skillhub_auth/src/main/java/com/example/auth/config/**,skillhub_auth/src/main/java/com/example/auth/controller/**,skillhub_auth/src/main/java/com/example/auth/entity/**,skillhub_auth/src/main/java/com/example/auth/exception/**,skillhub_auth/src/main/java/com/example/auth/repository/**
sonar.cpd.exclusions=skillhub_back/app/Http/Controllers/Api/FormationController.php,skillhub_auth/src/main/java/com/example/auth/client/**,skillhub_auth/src/main/java/com/example/auth/controller/**,skillhub_auth/src/main/java/com/example/auth/exception/**

sonar.php.coverage.reportPaths=skillhub_back/reports/coverage.xml
